/**
 * Web Worker for parsing large JSON tree files off the main thread.
 * Receives raw JSON string, processes it into a TreeSource, and posts back the result.
 *
 * Usage from main thread:
 *   const worker = new Worker(new URL('./parseWorker.ts', import.meta.url), { type: 'module' });
 *   worker.postMessage({ id, name, rawJson });
 *   worker.onmessage = (e) => { const treeSource = e.data; };
 */

// --- Duplicated processing logic (Workers can't import from the main bundle) ---

type NodeType = 'directory' | 'file' | 'link' | 'socket' | 'report' | 'fifo' | 'device';

interface TreeItem {
  type: NodeType;
  name: string;
  size?: number;
  mode?: string;
  prot?: string;
  uid?: number;
  user?: string;
  gid?: number;
  group?: string;
  time?: string;
  contents?: TreeItem[];
  id: string;
  parentPath?: string;
  depth: number;
  extension: string;
  treeSourceId: string;
}

interface TreeSource {
  id: string;
  name: string;
  importedAt: string;
  rawJson?: string;
  rootNodes: TreeItem[];
  directoriesCount: number;
  filesCount: number;
  totalSize: number;
}

/**
 * Iteratively processes raw JSON nodes into TreeItem objects.
 * Uses an explicit stack instead of recursion to avoid stack overflow on deeply nested trees.
 */
function processRawNodes(rawNodes: any[]): any[] {
  const rootResults: any[] = [];

  // Stack items: { raw node, parentContentsArray }
  type StackItem = {
    raw: any;
    target: any[];
  };

  const stack: StackItem[] = [];

  // Push root nodes in reverse order so they are processed in original order
  for (let i = rawNodes.length - 1; i >= 0; i--) {
    stack.push({ raw: rawNodes[i], target: rootResults });
  }

  while (stack.length > 0) {
    const { raw, target } = stack.pop()!;

    // Handle standalone error objects generated by 'tree' when directory permissions fail
    if (raw.error && !raw.name) {
      target.push({
        type: 'file',
        name: `⚠️ Error: ${raw.error}`,
        size: 0,
        depth: 0,
        extension: '',
        treeSourceId: ''
      });
      continue;
    }

    const name = (raw.name || 'unnamed').replace(/^\.\//, '');
    const processed: any = {
      type: raw.type || 'file',
      name,
    };

    if (typeof raw.size === 'number') processed.size = raw.size;
    if (raw.mode) processed.mode = raw.mode;
    if (raw.prot) processed.prot = raw.prot;
    if (raw.uid !== undefined) processed.uid = raw.uid;
    if (raw.user) processed.user = raw.user;
    if (raw.gid !== undefined) processed.gid = raw.gid;
    if (raw.group) processed.group = raw.group;
    if (raw.time) processed.time = raw.time;

    if (raw.contents && Array.isArray(raw.contents)) {
      processed.contents = [];
      // Push children in reverse order for correct processing order
      for (let i = raw.contents.length - 1; i >= 0; i--) {
        stack.push({
          raw: raw.contents[i],
          target: processed.contents,
        });
      }
    }

    target.push(processed);
  }

  return rootResults;
}

/**
 * Iteratively counts files, directories, and total size.
 */
function countNodesIterative(rootNodes: TreeItem[]): { files: number; dirs: number; size: number } {
  let files = 0;
  let dirs = 0;
  let size = 0;

  const stack = [...rootNodes];

  while (stack.length > 0) {
    const node = stack.pop()!;
    size += node.size || 0;

    if (node.type === 'directory') {
      dirs++;
      if (node.contents) {
        for (let i = 0; i < node.contents.length; i++) {
          stack.push(node.contents[i]);
        }
      }
    } else {
      files++;
    }
  }

  return { files, dirs, size };
}

// --- Worker message handler ---
// @ts-ignore
import clarinet from 'clarinet';

/**
 * Robustly inserts commas between adjacent JSON objects/arrays (e.g. `}{` or `][`)
 * that are missing a comma, which frequently happens in malformed outputs like from the `tree` command.
 */
function fixMissingCommas(chunk: string, state: { lastChar: string }): string {
  let text = chunk;
  const needRestore = state.lastChar === '}' || state.lastChar === ']';
  if (needRestore) {
    text = state.lastChar + text;
  }
  
  // Regex to match } or ] followed by optional whitespace followed by { or [
  // and insert a comma between them if not present.
  text = text.replace(/([\}\]])(\s*)([\{\[])/g, '$1,$2$3');
  
  if (needRestore) {
    if (text.charAt(1) === ',') {
      text = ',' + text.slice(2);
    } else {
      text = text.slice(1);
    }
  }
  
  const trimmed = text.trimEnd();
  if (trimmed.length > 0) {
    state.lastChar = trimmed.charAt(trimmed.length - 1);
  }
  
  return text;
}

function parseJsonStream(file: File | Blob): Promise<any> {
  return new Promise(async (resolve, reject) => {
    const parser = clarinet.parser();
    
    let rootValue: any = undefined;
    const stack: any[] = [];
    let currentContainer: any = null;
    let currentKey: string | undefined = undefined;

    parser.onvalue = (v: any) => {
      if (currentContainer === null) {
        rootValue = v;
      } else if (Array.isArray(currentContainer)) {
        currentContainer.push(v);
      } else {
        currentContainer[currentKey as string] = v;
      }
    };

    parser.onopenobject = (key?: string) => {
      const obj: any = {};
      if (currentContainer === null) {
        rootValue = obj;
      } else if (Array.isArray(currentContainer)) {
        currentContainer.push(obj);
      } else {
        currentContainer[currentKey as string] = obj;
      }
      stack.push(currentContainer);
      currentContainer = obj;
      currentKey = key;
    };

    parser.onkey = (key: string) => {
      currentKey = key;
    };

    parser.oncloseobject = () => {
      currentContainer = stack.pop();
    };

    parser.onopenarray = () => {
      const arr: any[] = [];
      if (currentContainer === null) {
        rootValue = arr;
      } else if (Array.isArray(currentContainer)) {
        currentContainer.push(arr);
      } else {
        currentContainer[currentKey as string] = arr;
      }
      stack.push(currentContainer);
      currentContainer = arr;
    };

    parser.onclosearray = () => {
      currentContainer = stack.pop();
    };

    parser.onerror = (err: any) => {
      reject(err);
    };

    parser.onend = () => {
      resolve(rootValue);
    };

    try {
      const stream = file.stream();
      const reader = stream.getReader();
      const decoder = new TextDecoder('utf-8');
      const streamState = { lastChar: '' };

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        let chunk = decoder.decode(value, { stream: true });
        
        // Fix any missing commas in this chunk (e.g. `}{"error":`)
        chunk = fixMissingCommas(chunk, streamState);
        
        parser.write(chunk);
      }
      // Ensure the decoder flushes properly if there are trailing bytes
      let finalChunk = decoder.decode(new Uint8Array(0));
      if (finalChunk) {
        finalChunk = fixMissingCommas(finalChunk, streamState);
        parser.write(finalChunk);
      }
      
      parser.close();
    } catch (err) {
      reject(err);
    }
  });
}

self.onmessage = async function (e: MessageEvent<{ id: string; name: string; file: File | Blob }>) {
  const { id, name, file } = e.data;

  try {
    const parsed = await parseJsonStream(file);
    const dataArray = Array.isArray(parsed) ? parsed : [parsed];
    const dataNodes = dataArray.filter((node: any) => node.type !== 'report');

    const rootNodes = processRawNodes(dataNodes);
    const counts = countNodesIterative(rootNodes);

    const rootNodesJson = JSON.stringify(rootNodes);

    (self as any).postMessage({
      success: true,
      result: {
        id,
        name,
        importedAt: new Date().toLocaleString(),
        rootNodesJson,
        directoriesCount: counts.dirs,
        filesCount: counts.files,
        totalSize: counts.size,
      }
    });
  } catch (err: any) {
    (self as any).postMessage({ success: false, error: err.message || err.toString() });
  }
};
